### ISSUE TITLE
VKObserver doesn't push TEdit or TMemo controls above the keyboard when at the bottom of a listbox/scrollable container (maybe other cases too)

### ISSUE THREAD

**Issue by MyBuzzTechnologies** [DelphiWorlds/Playground#21]
I tried various versions of this and could reliably reproduce when the control are in a TListBox control.

If you create a TListBox, aligned to client and fill with TListBoxItem so you have some at the very bottom of the device screen. Add a TEdit to one of those at the bottom well below the keyboard.

Run the app and tap the TEdit. It doesn't push the control up above the keyboard.

I've discovered that it's because the ContentBounds isn't being increased on the list box so there isn't enough "scroll" to push it up.

Adding some extra space to the bottom of the content bounds fixes this but the ideally the VKObserver needs to do this itself to avoid having to do this on every container.

procedure TForm2.listboxCalcContentBounds(Sender: TObject; var ContentBounds: TRectF);
begin
  ContentBounds.Bottom:=ContentBounds.Bottom + 400;
end;

Thanks

**Comment by DelphiWorlds** [comment]
As per the docs:

"The difference here is that it does not matter what the control is that contain the edits that result in the virtual keyboard showing, as long as the containing control is aligned to `Top`"

Since the ListBox is aligned to `Client`, changing the top margin does nothing. Your solution of changing the ContentBounds works OK for me on iOS. I've also added an `ActiveFrame` (as in the frame of the keyboard) property to `TVKObserver`, so you could use the `Height` property of `ActiveFrame` instead of hard-coding 400.

At this point, I'm averse to hooking into the OnCalcContentBounds event of the listbox - it's liable to become even more messy than the original implementation

**Comment by MyBuzzTechnologies** [comment]
Interestingly, changing the top margin on the TListBox does seem to work fine with set to Client - all except for the bottom rows of the list, but may just be coincidental effect. I agree with not hooking the OnCalcContentBounds, that would be a headache waiting to happen, I just wondered if there was some other way to do this but I suspect not.

Thanks for the info, I'll apply ActiveFrame.Height.
